# SwiftLint Configuration for Pet Progress iOS App

# Paths to include in linting
included:
  - App/Sources
  - Widget/Sources
  - SharedKit/Sources

# Paths to exclude from linting
excluded:
  - build
  - .build
  - Pods
  - Carthage
  - .git

# Rule configuration - Relaxed for enterprise codebase
disabled_rules:
  - trailing_whitespace
  - todo
  - implicit_return      # Allow explicit returns for clarity
  - force_unwrapping     # Allow in controlled contexts with proper error handling
  - force_try           # Allow in test and controlled contexts
  - empty_count         # Allow count comparisons for readability
  - redundant_string_enum_value  # Allow explicit enum values
  - for_where           # Allow traditional for loops
  - unused_setter_value # Allow in SwiftUI property wrappers
  - sorted_imports      # Allow flexible import ordering

opt_in_rules:
  - trailing_newline

# Custom rule settings - Enterprise scale appropriate
line_length:
  warning: 150
  error: 200
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true

function_body_length:
  warning: 80
  error: 120

type_body_length:
  warning: 400
  error: 600

file_length:
  warning: 800
  error: 1200

identifier_name:
  min_length:
    warning: 1
    error: 0
  max_length:
    warning: 40
    error: 60
  excluded:
    - id
    - x
    - y
    - z

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 2
  statement_level:
    warning: 5

# Custom rules disabled for enterprise codebase flexibility
# custom_rules:

reporter: "github-actions-logging"