name: PetProgress

options:
  minimumXcodeGenVersion: 2.37.0
  createIntermediateGroups: true
  xcodeVersion: "16.0"

configs:
  Debug: debug
  Release: release

settings:
  base:
    SWIFT_VERSION: 5.10
    IPHONEOS_DEPLOYMENT_TARGET: 16.0
    ENABLE_BITCODE: NO
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: "" # Simulator build; no signing
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES

fileGroups:
  - App
  - Shared
  - Widget
  - Entitlements

targets:
  PetProgress:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.PetProgress
        INFOPLIST_FILE: App/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    sources:
      - path: App
      - path: Shared
      - path: App/Resources
        type: folder
      - path: Shared/Resources
        type: folder
    resources:
      - path: App/Resources/Assets.xcassets
      - path: Shared/Resources/Assets.xcassets
    entitlements:
      path: Entitlements/App.entitlements
    dependencies:
      - target: PetProgressWidget
        embed: true

  PetProgressWidget:
    type: app-extension
    platform: iOS
    deploymentTarget: "16.0"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.PetProgress.Widget
        INFOPLIST_FILE: Widget/Info.plist
        NSEXTENSIONPOINTIDENTIFIER: com.apple.widgetkit-extension
    sources:
      - path: Widget
      - path: Shared
      - path: Widget/Resources
        type: folder
      - path: Shared/Resources
        type: folder
    resources:
      - path: Widget/Resources/Assets.xcassets
      - path: Shared/Resources/Assets.xcassets
    entitlements:
      path: Entitlements/Widget.entitlements
    dependencies: []   # <- IMPORTANT: no dependency on the App

schemes:
  PetProgress:
    build:
      targets:
        PetProgress: all
        PetProgressWidget: all
    run:
      config: Debug
      executable: PetProgress
    test:
      config: Debug
      gatherCoverageData: false
      targets: []
    archive:
      config: Release
