name: PetProgress
options:
  minimumXcodeGenVersion: 2.37.0
  createIntermediateGroups: true
  xcodeVersion: "16.0"
  deploymentTarget:
    iOS: "17.0"
packages: {}
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: 17.0
    SWIFT_VERSION: 5.10
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: ""
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
targets:
  PetProgressShared:
    type: framework
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yourco.petprogress.shared
        DEVELOPMENT_TEAM: YOUR_ACTUAL_TEAM_ID
        MACH_O_TYPE: mh_dylib
        DYLIB_INSTALL_NAME_BASE: "@rpath"
        SKIP_INSTALL: NO
        SWIFT_INSTALL_OBJC_HEADER: NO
        DEFINES_MODULE: NO
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGN_IDENTITY: ""
        PROVISIONING_PROFILE_SPECIFIER: ""
    info:
      path: Shared/Info.plist

  PetProgress:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: App
      - path: Entitlements
        optional: true
      - path: App/Resources
      - path: App/ErrorHandling
      - path: App/UI
      - path: App/Settings
    resources:
      - path: App/Resources/StageConfig.json
      - path: App/Resources/Assets.xcassets
      - path: Shared/Resources/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.hedgingmybets.PetProgress
        DEVELOPMENT_TEAM: YOUR_ACTUAL_TEAM_ID
        FRAMEWORK_SEARCH_PATHS: '$(inherited) $(BUILT_PRODUCTS_DIR)'
        SWIFT_INSTALL_OBJC_HEADER: NO
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGN_IDENTITY: ""
        PROVISIONING_PROFILE_SPECIFIER: ""
    info:
      path: App/Info.plist
      properties:
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UILaunchScreen:
          UIImageName: ""
        CFBundleDisplayName: PetProgress
        CFBundleURLTypes:
          - CFBundleURLName: petprogress
            CFBundleURLSchemes: [petprogress]
    entitlements:
      path: Entitlements/App.entitlements
    dependencies:
      - target: PetProgressShared
      - target: PetProgressWidget
        embed: true
    postBuildScripts: []
    scheme:
      testTargets: [PetProgressTests]

  PetProgressWidget:
    type: app-extension
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Widget
      - path: Entitlements
        optional: true
    resources:
      - path: Widget/Resources/StageConfig.json
      - path: Shared/Resources/Assets.xcassets
    info:
      path: Widget/Info.plist
      properties:
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).PetProgressWidgetBundle
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.hedgingmybets.PetProgress.widget
        DEVELOPMENT_TEAM: YOUR_ACTUAL_TEAM_ID
        LD_RUNPATH_SEARCH_PATHS: '$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks'
        FRAMEWORK_SEARCH_PATHS: '$(inherited) $(BUILT_PRODUCTS_DIR)'
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGN_IDENTITY: ""
        PROVISIONING_PROFILE_SPECIFIER: ""
    entitlements:
      path: Entitlements/Widget.entitlements
    dependencies:
      - target: PetProgressShared

  PetProgressTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yourco.petprogress.tests
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGNING_ALLOWED: NO
    dependencies:
      - target: PetProgress
      - target: PetProgressShared

schemes:
  PetProgress:
    build:
      targets:
        PetProgressShared: all
        PetProgress: all
        PetProgressWidget: all
        PetProgressTests: [test]
    test:
      gatherCoverageData: false
      testTargets:
        - name: PetProgressTests

