name: MyTaskList
options:
  bundleIdPrefix: com.mytasklist
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en
  groupSortPosition: top
  generateEmptyDirectories: false
  findCarthageFrameworks: false
  transitivelyLinkDependencies: false
  groupOrdering:
    - order: [SharedKit, App, Widget, Tests]

settings:
  base:
    # Team & Versioning
    DEVELOPMENT_TEAM: ""
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

    # Swift & Platform Settings
    SWIFT_VERSION: "5.10"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    SUPPORTS_MACCATALYST: true
    DERIVE_MACCATALYST_PRODUCT_BUNDLE_IDENTIFIER: true

    # Code Signing & Security
    CODE_SIGN_STYLE: Automatic
    ENABLE_HARDENED_RUNTIME: true

    # Build Performance Optimizations
    ENABLE_LIBRARY_EVOLUTION: false
    BUILD_LIBRARY_FOR_DISTRIBUTION: false
    SWIFT_COMPILATION_MODE: wholemodule

    # Advanced Swift Features - Reduced set for CI compatibility
    SWIFT_STRICT_CONCURRENCY: minimal

    # Code Quality & Warnings
    CLANG_ANALYZER_NONNULL: true
    CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION: true
    CLANG_ENABLE_MODULES: true
    CLANG_ENABLE_OBJC_ARC: true
    CLANG_ENABLE_OBJC_WEAK: true
    CLANG_WARN_DOCUMENTATION_COMMENTS: true
    CLANG_WARN_UNGUARDED_AVAILABILITY: true
    GCC_WARN_ABOUT_RETURN_TYPE: error
    GCC_WARN_UNDECLARED_SELECTOR: true
    GCC_WARN_UNINITIALIZED_AUTOS: aggressive
    CLANG_WARN_DIRECT_OBJC_ISA_USAGE: error
    RUN_CLANG_STATIC_ANALYZER: true

    # Performance & Optimization
    DEAD_CODE_STRIPPING: true
    STRIP_INSTALLED_PRODUCT: true
    SEPARATE_STRIP: true
    DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
    ENABLE_NS_ASSERTIONS: true
    ENABLE_STRICT_OBJC_MSGSEND: true
    GCC_C_LANGUAGE_STANDARD: gnu17
    GCC_NO_COMMON_BLOCKS: true
    CLANG_CXX_LANGUAGE_STANDARD: gnu++20

    # Accessibility & Localization
    ENABLE_TESTABILITY: true
    GENERATE_INFOPLIST_FILE: true

targets:
  SharedKit:
    type: framework
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: SharedKit/Sources/SharedKit
        buildPhase: sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.petprogress.SharedKit
        DEFINES_MODULE: true
        SKIP_INSTALL: true
        ENABLE_TESTING_SEARCH_PATHS: false
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_CFBundleDisplayName: SharedKit

  PetProgress:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: App/Sources
        buildPhase: sources
    resources:
      - path: App/Assets.xcassets
        buildPhase: resources
      - path: App/PrivacyInfo.xcprivacy
        buildPhase: resources
      - path: App/LaunchScreen.storyboard
        buildPhase: resources
    dependencies:
      - target: SharedKit
      - target: PetProgressWidget
        embed: true
    entitlements:
      path: App/PetProgress.entitlements
    settings:
      base:
        PRODUCT_NAME: PetProgress
        PRODUCT_BUNDLE_IDENTIFIER: com.petprogress.app
        INFOPLIST_FILE: App/Info.plist
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: true
        ENABLE_TESTING_SEARCH_PATHS: false
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

  PetProgressWidget:
    type: app-extension
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Widget/Sources
        buildPhase: sources
    resources:
      - path: Widget/Assets.xcassets
        buildPhase: resources
    dependencies:
      - target: SharedKit
    entitlements:
      path: Widget/PetProgressWidget.entitlements
    settings:
      base:
        PRODUCT_NAME: PetProgressWidget
        PRODUCT_BUNDLE_IDENTIFIER: com.petprogress.app.PetProgressWidget
        INFOPLIST_FILE: Widget/Info.plist
        ENABLE_TESTING_SEARCH_PATHS: false
        SKIP_INSTALL: true

  PetProgressTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Tests
        buildPhase: sources
    dependencies:
      - target: PetProgress
      - target: SharedKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.petprogress.PetProgressTests
        BUNDLE_LOADER: $(TEST_HOST)
        TEST_HOST: $(BUILT_PRODUCTS_DIR)/PetProgress.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/PetProgress
        ENABLE_TESTING_SEARCH_PATHS: true

schemes:
  PetProgress:
    build:
      targets:
        PetProgress: all
        PetProgressWidget: all
        SharedKit: all
    run:
      config: Debug
      executable: PetProgress
    test:
      config: Debug
      targets:
        - name: PetProgressTests
          parallelizable: true
          randomExecutionOrder: true
    archive:
      config: Release