name: PetProgress
options:
  bundleIdPrefix: com.petprogress
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en
  groupSortPosition: top
  generateEmptyDirectories: false
  findCarthageFrameworks: false
  transitivelyLinkDependencies: false
  groupOrdering:
    - order: [SharedKit, App, Widget, Tests]

settings:
  base:
    DEVELOPMENT_TEAM: ""
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    CODE_SIGN_STYLE: Automatic

targets:
  SharedKit:
    type: framework
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: SharedKit/Sources/SharedKit
        buildPhase: sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.petprogress.SharedKit
        DEFINES_MODULE: true
        SKIP_INSTALL: true
        ENABLE_TESTING_SEARCH_PATHS: false
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_CFBundleDisplayName: SharedKit

  PetProgress:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: App/Sources
        buildPhase: sources
    resources:
      - path: App/Assets.xcassets
        buildPhase: resources
    dependencies:
      - target: SharedKit
      - target: PetProgressWidget
        embed: true
    entitlements:
      path: App/PetProgress.entitlements
    settings:
      base:
        PRODUCT_NAME: PetProgress
        PRODUCT_BUNDLE_IDENTIFIER: com.petprogress.app
        INFOPLIST_FILE: App/Info.plist
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: true
        ENABLE_TESTING_SEARCH_PATHS: false
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

  PetProgressWidget:
    type: app-extension
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Widget/Sources
        buildPhase: sources
    resources:
      - path: Widget/Assets.xcassets
        buildPhase: resources
    dependencies:
      - target: SharedKit
    entitlements:
      path: Widget/PetProgressWidget.entitlements
    settings:
      base:
        PRODUCT_NAME: PetProgressWidget
        PRODUCT_BUNDLE_IDENTIFIER: com.petprogress.app.PetProgressWidget
        INFOPLIST_FILE: Widget/Info.plist
        ENABLE_TESTING_SEARCH_PATHS: false
        SKIP_INSTALL: true

  PetProgressTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Tests
        buildPhase: sources
    dependencies:
      - target: PetProgress
      - target: SharedKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.petprogress.PetProgressTests
        BUNDLE_LOADER: $(TEST_HOST)
        TEST_HOST: $(BUILT_PRODUCTS_DIR)/PetProgress.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/PetProgress
        ENABLE_TESTING_SEARCH_PATHS: true

schemes:
  PetProgress:
    build:
      targets:
        PetProgress: all
        PetProgressWidget: all
        SharedKit: all
    run:
      config: Debug
      executable: PetProgress
    test:
      config: Debug
      targets:
        - name: PetProgressTests
          parallelizable: true
          randomExecutionOrder: true
    archive:
      config: Release