name: iOS Build

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'ios-native/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'ios-native/**'

jobs:
  build:
    name: iOS Build and Test
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Show Xcode Version
      run: xcodebuild -version

    - name: Cache Swift Packages
      uses: actions/cache@v3
      with:
        path: ios-native/.build
        key: ${{ runner.os }}-spm-${{ hashFiles('ios-native/**/Package.swift') }}
        restore-keys: ${{ runner.os }}-spm-

    - name: Build iOS Project
      run: |
        cd ios-native
        xcodebuild -scheme PetProgress \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \
          -configuration Debug \
          build-for-testing

    - name: Run Tests
      run: |
        cd ios-native
        xcodebuild -scheme PetProgress \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \
          -configuration Debug \
          test-without-building